vscode:
  extensions:
    - prateekmahendrakar.prettyxml@0.6.0:RRnc8ea0lOEUMAA6zejQjg==
    - ritwickdey.liveserver@5.6.1:5Mhl1RgVVDcIym163x8r+w==
    - esbenp.prettier-vscode@5.9.2:/ZjVG4nabMGxTqOcyglnfQ==